### ISSUE TITLE
Copy examples to respective repos.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/viz-library#103]
Migrate the following 5 examples
- [x] Example 12 -> https://rhoinc.github.io/web-codebook/test-page/explorer/
- [x] Example 11 -> https://rhoinc.github.io/safety-explorer-suite/test-page/queries/
- [x] Example 16 -> https://rhoinc.github.io/safety-outlier-explorer/test-page/hyslaw/
- [x] Example 17 -> https://rhoinc.github.io/safety-outlier-explorer/PopulationExplorer/testpage
- [x] Example 18 -> https://bl.ocks.org/jwildfire/raw/f2bd58b09852a37dcb131ba43507fab4/

**Comment by jwildfire** [comment]
Also update the URL for the redirect in `/examples/0018`
