### ISSUE TITLE
data download links are not working

### ISSUE THREAD

**Issue by srosanba** [RhoInc/viz-library#29]
AE and ADAE were both tried, got 404 errors for both

https://rhoinc.github.io/viz-library/data/safetyData-queries/ADAE.csv
vs.
https://rhoinc.github.io/viz-library/safetyData-queries/ADAE.csv

**Comment by jwildfire** [comment]
Pretty sure the issue is because of a buggy relative path in the code ... will clean it up.

**Comment by jwildfire** [comment]
Yep didn't fix the path when I moved the links from `./data/index.html` to just `./index.html` [here](
![image](https://cloud.githubusercontent.com/assets/3680095/26273491/3dd7d950-3ce6-11e7-965b-1a22d7644097.png)
)
