### ISSUE TITLE
Broken Links to Download Data

### ISSUE THREAD

**Issue by mhickle** [RhoInc/viz-library#53]
The following charts have links to download data that either point you back to the Viz Library homepage or show an error "file not found" message:

Ordered Precipitation Heatmap
Spike Histogram Demo
Web Codebook Demo
Interactive Scatter Plot Lattice with Viral Signs Data
Unemployment Trends with a Multivariate Time Series
Simple Interactive Bar Chart (results data = null)
Safety Explorer Suite - Single Page
Web Codebook Explorer
Safety Explorer - Default Configuration

**Comment by jwildfire** [comment]
fixed in v1.0.1
