### ISSUE TITLE
Nav not working on Safety Explorer examples

### ISSUE THREAD

**Issue by rtbailey** [RhoInc/viz-library#54]
The nav bar on the Safety Explorer Chart examples in the Viz Library (Default and Query Data versions) don't appear to be working. Chrome renders nothing when I click on one of the other charts. Firefox spits out: "301 Moved Permanently"

**Comment by samussiah** [comment]
![image](https://user-images.githubusercontent.com/5428548/29879444-0ee18460-8d73-11e7-895d-c1213a65bf8c.png)

**Comment by jwildfire** [comment]
fixed in v1.0.1
