### ISSUE TITLE
The list of the prototypes that are not displaying

### ISSUE THREAD

**Issue by nandriychuk** [RhoInc/viz-library#80]
The following prototypes are not displaying and need to be fixed:
- Movies With Friends
- Safety Outlier Explorer - Example
- D3 Formatting Example
- Baseball Statistics Histogram III - Webcharts-templates
- Baseball Statistics Histogram II - Webcharts-templates 
- Baseball Statistics Histogram - Webcharts-templates

**Comment by jwildfire** [comment]
These are old and non-essential, so just going to delete these from the list and close this issue out.
